"""create entitlements table

Revision ID: 43a12d6e0cb7
Revises: b7bf49fe0991
Create Date: 2025-11-12 15:45:00.700246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43a12d6e0cb7'
down_revision: Union[str, None] = 'b7bf49fe0991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'entitlements',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('subscription_active', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('look_book_remaining', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('video_remaining', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('credit_cached', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entitlements')
    # ### end Alembic commands ###
