"""update point_usage add project_id and usage_method

Revision ID: 69f8be8a3be2
Revises: 75a29732ee83
Create Date: 2025-11-12 15:14:29.684221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69f8be8a3be2'
down_revision: Union[str, None] = '75a29732ee83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_usage', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('point_usage', sa.Column('usage_method', sa.String(length=32), nullable=True))
    
    # 기존 데이터에 기본값 설정
    op.execute("UPDATE point_usage SET usage_method = 'manual' WHERE usage_method IS NULL")
    
    # 이제 NOT NULL 제약조건 추가
    op.alter_column('point_usage', 'usage_method', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_usage', 'usage_method')
    op.drop_column('point_usage', 'project_id')
    # ### end Alembic commands ###
