"""create points tables

Revision ID: 75a29732ee83
Revises: f362464c7b86
Create Date: 2025-11-12 14:53:11.799271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75a29732ee83'
down_revision: Union[str, None] = 'f362464c7b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('usage_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('look_book_ticket', sa.Integer(), nullable=False),
    sa.Column('video_ticket', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    op.drop_table('point_usage')
    # ### end Alembic commands ###
