"""create users table

Revision ID: b7bf49fe0991
Revises: 5383226930be
Create Date: 2025-11-12 15:41:57.615753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7bf49fe0991'
down_revision: Union[str, None] = '5383226930be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
