"""update subscription_record fk cascade

Revision ID: db07085767fb
Revises: 43a12d6e0cb7
Create Date: 2025-11-12 15:51:09.727363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db07085767fb'
down_revision: Union[str, None] = '43a12d6e0cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_record_user_id_fkey', 'subscription_record', type_='foreignkey')
    op.drop_constraint('subscription_record_subscription_id_fkey', 'subscription_record', type_='foreignkey')
    op.create_foreign_key('subscription_record_user_id_fkey', 'subscription_record', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subscription_record_subscription_id_fkey', 'subscription_record', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_record_subscription_id_fkey', 'subscription_record', type_='foreignkey')
    op.drop_constraint('subscription_record_user_id_fkey', 'subscription_record', type_='foreignkey')
    op.create_foreign_key('subscription_record_subscription_id_fkey', 'subscription_record', 'subscriptions', ['subscription_id'], ['id'])
    op.create_foreign_key('subscription_record_user_id_fkey', 'subscription_record', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
